### ISSUE TITLE
Issue with Windows path?

### ISSUE THREAD

**Issue by UnderTheCarpet** [b3u/vscode-backlinks-panel#3]
## Expected Behavior
The backlinks panel stays empty. Instead I get a toast with
`ENOENT: no such file or directory, scandir '/c:/Users/foo/bla - boo/notes'`

## Actual Behavior
No error message

## Possible Fix
Maybe Windows path names are note handled properly? Note the leading `/` in the toast.

## Steps to Reproduce
Open a markdown file on a Windows (OneDrive Sync)-folder

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Version used: 0.2.0
* VS Code version: 1.45.1
* Operating System and version: Windows 10 1909

**Comment by binyamin** [comment]
@fkjogu Thanks so much for the issue. I'll take a look.

**Comment by binyamin** [comment]
fixed in b7c6866b0a5a7a9a6b97658f5aded3f84c848ded

**Comment by binyamin** [comment]
@fkjogu Just published a fix; try it now.

**Comment by UnderTheCarpet** [comment]
Works! Thank you
